export {
  DIALOGUE,
  SHARED_DIALOGUE_WHEN,
  SHARED_APPROACH_WHEN,
  SHARED_ENCOUNTER_TEASERS,
  SHARED_MISSED_LINES,
  SHARED_WRONG_GUESS_LINES,
  SHARED_WINNER_LINES,
} from "./dialogue/index.js";
