[providers]
runtime = "nodejs"

[phases.setup]
nixpkgs = [
  "cairo",
  "pango",
  "pixman",
  "fontconfig",
  "fonts-liberation",
  "fonts-dejavu",
  "xorg.xfonts-encodings",
  "xorg.xfonts-utils"
]

[phases.build]
cmds = ["npm run build || true"]
