[providers]
runtime = "nodejs"

[phases.setup]
nixpkgs = [
  "cairo",
  "pango",
  "pixman",
  "fontconfig",
  "fontconfig-data",
  "fonts-liberation",
  "fonts-dejavu"
]

[phases.build]
cmds = ["npm run build || true"]
