[providers]
runtime = "nodejs"

[phases.setup]
nixpkgs = [
  "cairo",
  "pango",
  "pixman",
  "fontconfig",
  "fontconfig.bin",
  "fonts-liberation",
  "fonts-dejavu",
  "xorg.xfonts-encodings",
  "xorg.xfonts-utils",
  "xorg.fontbdftopcf"
]

[phases.build]
cmds = [
  "fc-cache -f -v || true",
  "npm run build || true"
]
