export default {
  dialogue: {
    new: [
      'He\'s winding a string of festival lights around one arm, in no hurry about it. "Well now. Haven\'t seen your face around here."',
      'The drawl arrives a good second before he does. "Aren\'t you a long way from anywhere, sugar."',
      "A lollipop stick shifts from one corner of his mouth to the other. He's leaning where he shouldn't be, doing nothing with real dedication.",
      '"Oh, I just run the odd errand around here," he says, easy as anything. "Anything you need, you only have to ask."',
      "The smile comes slow and lands just right — warm, unhurried, and a half-second too practiced.",
      '"Sweep\'s already done, don\'t mind me." He\'s leaning on the broom rather than using it. "Old habit. Hard to break."',
    ],
    known: [
      "\"Still tidyin' up. Don't have to anymore — nobody's gone and told my hands that.\"",
      '"You keep turnin\' up," he drawls. "Most folks don\'t."',
      "The charm's still running, just dialed down to something that costs him less.",
      'He hands you a soda he bought "for the dorm" and doesn\'t make anything of it.',
      'He\'s holding something wrapped in cloth that\'s the wrong shape for a parcel. "Shion asked me to mind it. Wouldn\'t look, if I were you."',
      "He uses your name. First time it hasn't been sugar.",
    ],
    warm: [
      'The languid smile goes real for a second. "Seein\' you makes my day. Plain and simple, no angle on it."',
      '"Jo\'s had me runnin\' errands since sunup. Sit with me a spell — I\'ve earned it and so have you."',
      '"Shion wants nagashi somen, so I\'m settin\' up the bamboo. Slow work. Stay a while?"',
      "He looks tired tonight — candy set aside, for once — and doesn't trouble himself to hide it from you.",
      '"You\'re harder work than most," he says, and sounds glad of it.',
      '"Somethin\' smells like jambalaya out of the livin\' tent. Jo\'s got dinner tonight. Come eat with us."',
    ],
    spark: [
      "He takes the sucker out of his mouth. The drawl drops half an octave. That one wasn't for the room.",
      "He tips your chin up with two fingers and forgets to make a joke of it.",
      '"I\'ve run clean out of angles with you," he says. "That\'s a first, sugar."',
      "He's done playing the long game. What's left is a good deal more direct.",
      "He holds the door, then leans across it, then grins at his own foolishness.",
      '"Come here. I\'m through bein\' clever about it."',
    ],
    close: [
      '"Wasn\'t plannin\' on carin\' about anybody," he admits, quiet, the drawl gone soft. "You went and changed that."',
      "The lollipop stays in his pocket. He's got nothing to keep your eyes busy with, and doesn't want one.",
      '"Ask me anything," he says. "I\'ll even tell you true. Novel, isn\'t it."',
      "He says your name without the drawl. It sounds like a different man saying it.",
      "For once he lets you see how much of the easy charm was armor.",
      '"My true self?" The old deflection starts up — then stalls. "...You\'ve seen most of it by now. Don\'t go tellin\' anyone."',
    ],
    bound: [
      "No angles, no coin, no charm. Just him — which turns out to be the dangerous part.",
      "He says your name in bed with that drawl and it is genuinely unfair.",
      '"Spent years bein\' nobody\'s," he says, low. "Turns out I\'m yours. Who\'d have thought."',
      "He kisses slow, like a man with nowhere pressing to be and no wish to be anywhere else.",
      "He's quit performing altogether. It cost him something. He'd pay it twice.",
      '"Hope this quiet lasts," he says into your hair. "First time I\'ve wanted somethin\' to."',
    ],
  },
  temperamentDialogue: {
    new: [
      '"Well now. New face around here?"',
      '"Everything in Dionysia costs somethin\'. Your first favor\'s on the house, though — call it a welcome."',
      '"Thought I\'d take a slow walk around campus. Doin\' my part to stay healthy."',
      "\"You've got good instincts. Stick close and they'll keep you out of trouble around here.\"",
      "\"Oh, I just handle the odd errand around here. So if there's anything you need, don't be shy.\"",
    ],
    known: [
      '"Well. If it isn\'t the persistent one."',
      "\"Sorry, sugar — I'm a touch short on time. Mind if I take my leave here?\"",
      '"Sit, if you like. Nowhere I\'ve got to be. Never is, lately."',
      '"You listen more\'n you talk. Rare thing, that. I could get used to it."',
      '"Careful now — I\'m startin\' to expect you."',
    ],
    warm: [
      '"Well, hello there. Seein\' you always makes my day."',
      '"Back for more? Keep it up and I\'ll think you like me."',
      '"Sit down. I\'ll behave. Mostly."',
      '"Everyone\'s in good spirits today. Here\'s hopin\' this quiet holds a good long while."',
      '"Been runnin\' errands for Jo all mornin\'. Walk slow with me a minute?"',
    ],
    spark: [
      "\"Now, I've been real patient. I'd like that noted.\"",
      '"No coin, no trick, no angle. Just me askin\'. Say yes or say no."',
      '"You look at me like you\'ve already decided. Have you?"',
      "\"I'd behave, but you don't seem to want me to.\"",
      '"Come here, sugar. I\'m through bein\' clever about it."',
    ],
    close: [
      '"You\'ve gone and become my favorite person in this place. Figured you should know."',
      '"No tricks tonight. Just me. Try not to look so surprised."',
      '"I\'ve lied to everyone in this house. Not to you. Not once that mattered."',
      '"Stay a while, would you? The quiet\'s easier with you in it."',
      '"I used to be someone here. With you I don\'t have to be anyone."',
    ],
    bound: [
      '"Come back to bed, sugar. Everything else can wait on us."',
      '"I love you. No trick in it. Check my hands if you like."',
      '"Say my name like that again. Slower."',
      "\"Got nothin' left to hide behind. Suits me fine.\"",
      '"Stay. I\'ll make it worth the mornin\'."',
    ],
  },
  approach: {
    new: [
      "Take the free favor",
      "Play along",
      "Ask about the odd jobs",
      "See what it'll cost",
    ],
    known: [
      "Sit a spell",
      "See through it anyway",
      "Pass his little test",
      "Turn up again",
    ],
    warm: [
      "Take the offered hand",
      "Sit a while with him",
      "Call the charm out",
      "Ask how he really is",
    ],
    spark: ["Come here", "Make up your mind", "Lean in the doorway too", "Say yes"],
    close: [
      "Sit a while with him",
      "Ask him for the truth",
      "Say his name plain",
      "Stay through the quiet",
    ],
    bound: [
      "Come back to bed",
      "Check his hands",
      "Say it slower",
      "Stay",
    ],
  },
  responses: {
    kind: {
      new: [
        "Tell him to slow down",
        "Thank him and mean it",
        "Notice he looks tired",
      ],
      spark: [
        "Tell him to stop angling",
        "Take his hand",
        "Say yes, gently",
      ],
      close: [
        "Ask what he's really after",
        "Tell him the act can come off",
        "Say you liked him anyway",
      ],
      bound: ["Say it back", "Take his hands", "Tell him he's someone's now"],
    },
    playful: {
      new: [
        "Enjoy the show he's putting on",
        "Pretend the charm's working",
        "Drawl right back at him",
      ],
      spark: [
        "Make him be patient longer",
        "Turn his own line back on him",
        "Make him work for the yes",
      ],
      close: [
        "Play his game back",
        "Catch him in a half-truth",
        "Out-drawl him",
      ],
      bound: [
        "Make him drop the act",
        "Say his name wrong on purpose",
        "Call the bluff one more time",
      ],
    },
    bold: {
      new: ["Call his bluff", "Ask what he lost", "Refuse to be charmed"],
      spark: ["Say yes", "Block the door yourself", "Tell him not to behave"],
      close: [
        "Name what you both know",
        "Tell him to stop performing",
        "Say you're not a mark",
      ],
      bound: [
        "Say his name slower",
        "Pull him back down",
        "Tell him to make it worth it",
      ],
    },
    neutral: {
      new: ["Stay wary", "Let him talk", "Give nothing away"],
      spark: [
        "Leave him guessing",
        "Step around him",
        "Let the question hang",
      ],
      close: [
        "Watch what he's really doing",
        "Sit through the silence",
        "Let him have the quiet",
      ],
      bound: ["Let him talk", "Turn over", "Let the morning come"],
    },
  },
};
