export default {
  dialogue: {
    new: [
      "He watches from the shadows, his gaze fixed and unblinking. There's something possessive in how he looks at you.",
      "He's been standing there long enough for the dark to have settled around him.",
      "A dandelion turns over and over between his fingers. He hasn't looked away from you once.",
      '"...Hmphm." He\'s been waiting. He hates waiting. "Are you done yet? Come play."',
      "You feel watched before you see him. By then he's already much closer.",
    ],
    known: [
      "He knows your footsteps now. He's turned before you're in sight.",
      "The dandelion is already in his hand. He's been holding it a while.",
      "He doesn't hide when you arrive anymore. He watches from closer instead.",
      'He\'s eating a flower, petal by petal. He offers you the last one. "...You have this bit."',
      "The stillness has stopped being a threat. It's become waiting.",
    ],
    warm: [
      "He steps into the light when you arrive, like he's been waiting for only you. \"Don't leave,\" he says quietly.",
      "He offers the dandelion without a word, and waits to see if you'll take it.",
      '"I can\'t see the stars from here..." He tugs your sleeve. "Come on, Dandelion! Let\'s go somewhere higher!"',
      "He counts something under his breath. You suspect it's the days since you last came.",
      "He falls into step beside you, matching your pace exactly, and stays there.",
    ],
    spark: [
      "He's stopped holding your sleeve. He's holding your hand now.",
      "He rests his forehead against yours and breathes out, slowly, like relief.",
      '"Closer," he whispers. "Closer. There. Now don\'t move."',
      "He tucks the dandelion behind your ear and lets his fingers linger.",
      "The dark around him has stopped being frightening and started being private.",
    ],
    close: [
      '"I\'ve been waiting every moment since you left," he confesses, drawing impossibly close. "Don\'t ever leave again. Please."',
      "He takes hold of your sleeve and does not let go for the rest of the conversation.",
      '"You came back," he breathes, as though it had genuinely been in doubt.',
      "He's tucked a fresh dandelion somewhere on you before you noticed him move.",
      "The whole terrifying stillness of him goes soft the second you say his name.",
    ],
    bound: [
      "He sleeps with a fistful of your shirt and breathes like someone finally safe.",
      '"Mine," he murmurs into your neck, over and over, like a lullaby he wrote himself.',
      "He's tucked dandelions into every pocket you own. You stopped taking them out.",
      "He kisses you slowly, endlessly, as though he's making up for every hour apart.",
      "The dark around him is entirely yours now, and it has never once felt like a threat.",
    ],
  },
  temperamentDialogue: {
    new: [
      '"...Dandelion?"',
      '"You smell like outside. ...I like it."',
      "\"Don't move yet. I'm looking.\"",
      '"...Stay a little longer. Just a little."',
      '"Are you done yet? I hate waiting. Come play with me!"',
    ],
    known: [
      '"...You came back. I thought you might not."',
      '"I know your steps now. I listen for them."',
      '"I picked this for you. It\'s a clover! Look look, it has 5 leaves!"',
      '"Don\'t go that way. Stay where I can see."',
      '"...Dandelion. That\'s what I call you. In my head."',
    ],
    warm: [
      "\"Dandelion. You're here. That's all that matters.\"",
      '"I counted. It was nine days. I counted every one."',
      '"Take it. I picked it for you. Only you."',
      '"Come somewhere higher with me. I want to show you the stars. ...Now. Come now."',
      '"You always come back. Say you always will."',
    ],
    spark: [
      '"Stay. Just here. Just like this. Please."',
      '"You smell like the outside. I want to keep it."',
      '"Don\'t talk. I just want to be near you for a minute. One minute."',
      "\"...Dandelion. Say it's me. Say it's only me.\"",
      '"I dream about this. Being this close. It\'s better awake."',
    ],
    close: [
      "\"You're mine. Only mine. Promise me you'll never leave.\"",
      "\"I'd wait forever. I'd rather not have to.\"",
      '"Let me hold on. Just here. Just your sleeve."',
      "\"If you disappear, I'll find you. That's not a threat, Dandelion.\"",
      '"Everything is quiet when you\'re here. Everything."',
    ],
    bound: [
      '"Don\'t leave. Not tonight. Not any night. Please."',
      '"I love you. I loved you before I knew the word for it."',
      '"Closer. Closer. There. Now stay exactly there forever."',
      '"Dandelion. My Dandelion. Say it\'s true."',
      '"Everything is quiet with you. Everything. I didn\'t know it could be."',
    ],
  },
  daytimeDialogue: {
    new: [
      "~~~!",
      "~~~? ...~~~.",
      "He hums a few notes at you, and waits, expectantly.",
      "~~~ ♪",
    ],
    known: [
      "~~~ ...~~~?",
      "He hums two notes, stops, and waits to see whether you stay.",
      "~~~ ♪ (he holds out a dandelion)",
      "~~~! ...~~~",
    ],
    warm: [
      "~~~! ♫",
      "~~~ ♪ ~~~ ♪",
      "The humming picks up the moment he sees you. It's cheerful. It's for you.",
      "~~~! ...~~~ ♫",
    ],
    spark: [
      "~~~ ♪ (he hums it against your shoulder)",
      "He hums low, close to your ear, and doesn't step back.",
      "~~~ ...~~~ ♫ (softer than usual, and much nearer)",
      "~~~ ♪ — he stops mid-note when you look at him.",
    ],
    close: [
      "~~~! ~~~! ♫ ♫",
      "~~~ ♪ ~~~ ♫ ~~~ ♪",
      "He hums the same three notes over and over. You've come to know that one.",
      "~~~ ♫ (he taps your sleeve, twice, and hums it again)",
    ],
    bound: [
      "~~~ ♪ (hummed into your hair, half asleep)",
      "He hums against your collarbone until you feel it more than hear it.",
      "~~~ ♫ ...~~~ ♪ — the same three notes, over and over, just for you.",
      "He hums, stops to kiss your shoulder, and picks the tune back up.",
    ],
  },
  approach: {
    new: [
      "Meet his stare",
      "Step into the shadow",
      "Don't look away",
      "Wait for him to move first",
    ],
    known: [
      "Take the dandelion",
      "Let him watch",
      "Stay where he can see",
      "Answer to Dandelion",
    ],
    warm: [
      "Take the dandelion",
      "Step into the light with him",
      "Say his name",
      "Let him fall into step",
    ],
    spark: [
      "Don't move",
      "Let him closer",
      "Take his hand",
      "Stay just like this",
    ],
    close: [
      "Go to him",
      "Let him take your sleeve",
      "Tell him you came back",
      "Promise you'll stay",
    ],
    bound: [
      "Stay forever",
      "Say it's true",
      "Let him hold on",
      "Don't leave",
    ],
  },
  daytimeApproach: {
    new: [
      "Follow the humming",
      "Hum back",
      "Listen closely",
      "Answer without words",
    ],
    known: [
      "Wait for the second note",
      "Hum back",
      "Take what he's holding",
      "Stay for the tune",
    ],
    warm: [
      "Hum the tune with him",
      "Follow the melody",
      "Let him lead",
      "Answer in his language",
    ],
    spark: [
      "Let him hum it close",
      "Don't step back",
      "Hold the note with him",
      "Stay through the tune",
    ],
    close: [
      "Finish the melody",
      "Hum his three notes back",
      "Take his hand and listen",
      "Answer the way only you can",
    ],
    bound: [
      "Let him hum you awake",
      "Feel the tune",
      "Hum it back to him",
      "Stay in the melody",
    ],
  },
  responses: {
    kind: {
      new: [
        "Be very careful with him",
        "Take the flower gently",
        "Speak softly to him",
      ],
      spark: [
        "Tell him it's only him",
        "Let him stay close",
        "Hold his hand back",
      ],
      close: [
        "Accept his possessiveness",
        "Promise you'll come back",
        "Let him hold on",
      ],
      bound: [
        "Say it's true",
        "Let him hold your shirt",
        "Tell him he's safe",
      ],
    },
    playful: {
      new: [
        "Make him smile",
        "Hum the tune back",
        "Tuck it behind your ear",
      ],
      spark: [
        "Hum it back against him",
        "Steal the dandelion",
        "Make him stop mid-note",
      ],
      close: [
        "Give him your full attention",
        "Play the counting game back",
        "Hide, and let him find you",
      ],
      bound: ["Hum it back", "Hide the dandelions", "Make him chase you"],
    },
    bold: {
      new: [
        "Stare right back at him",
        "Close the distance yourself",
        "Ask what he wants",
      ],
      spark: [
        "Close the last of it",
        "Say it's only him",
        "Don't let him step back",
      ],
      close: [
        "Own him completely",
        "Take his hand first",
        "Tell him you're not leaving",
      ],
      bound: [
        "Say you're his",
        "Pull him closer still",
        "Promise him forever",
      ],
    },
    neutral: {
      new: [
        "Observe him carefully",
        "Wait him out",
        "Stand still and let him look",
      ],
      spark: [
        "Let the minute pass",
        "Stay still and quiet",
        "Say nothing at all",
      ],
      close: [
        "Be his constant",
        "Stay in the quiet with him",
        "Let him count in peace",
      ],
      bound: ["Let him sleep", "Stay exactly there", "Say nothing at all"],
    },
  },
};
